
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Jul 15 15:13:46 CST 2024
//----------------------------------------------------

package sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SHOW = 15;
  public static final int ISCHAR = 22;
  public static final int CHAR = 32;
  public static final int CONCAT = 30;
  public static final int SECONDKEY = 26;
  public static final int NONULO = 27;
  public static final int LPAREN = 28;
  public static final int INT = 35;
  public static final int NONULL = 17;
  public static final int UPDATE = 7;
  public static final int DELETE = 8;
  public static final int WHERE = 9;
  public static final int NOIGUAL = 20;
  public static final int RPAREN = 29;
  public static final int IDENTIFICADOR = 36;
  public static final int NOT = 12;
  public static final int AND = 18;
  public static final int IGUAL = 21;
  public static final int OR = 19;
  public static final int REFERENCES = 14;
  public static final int SELECT = 5;
  public static final int DIGIT = 34;
  public static final int EOF = 0;
  public static final int GROUP = 10;
  public static final int TABLE = 4;
  public static final int error = 1;
  public static final int COMENTARIO = 37;
  public static final int NULL = 16;
  public static final int ERROR = 38;
  public static final int PCOMA = 31;
  public static final int FROM = 11;
  public static final int ISSTRING = 23;
  public static final int INSERT = 6;
  public static final int CREATE = 2;
  public static final int ORDER = 13;
  public static final int DATABASE = 3;
  public static final int BOOLEANO = 24;
  public static final int STRING = 33;
  public static final int PRIMARYKEY = 25;
}

